export const ACCESS_TOKEN_EXPIRING = 'ACCESS_TOKEN_EXPIRING';
export const ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED';
export const USER_LOADED = 'USER_LOADED';
export const USER_UNLOADED = 'USER_UNLOADED';
export const SILENT_RENEW_ERROR = 'SILENT_RENEW_ERROR';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';
export const USER_SESSION_CHANGED = 'USER_SESSION_CHANGED';
